### ISSUE TITLE
Failing to build on Ubuntu 18.04

### ISSUE THREAD

**Issue by richardcrossley** [ggodd/xview-64bit#10]
Hi,

Thanks for providing a 64 version of XView, a desktop I enjoyed using in my youth. I installed Ubuntu 18.04 in a virtual machine and performed the follow to build the source code:

```
sudo apt-get install build-essential git libboost-all-dev xutils-dev libx11-dev libxext-dev libncurses5-dev libxt-dev bison libxpm-dev

git clone https://github.com/ggodd/xiew-64bit.git

cd xview-64bit

sudo bash ./Build-LinuxXView.bash.amd64 all
```

Whilst compiling, the following error is given, and I am uncertain how to proceed.

```
y.tab.c: In function ‘yyparse’:
y.tab.c:1362:16: warning: implicit declaration of function ‘yylex’ [-Wimplicit-function-declaration]
y.tab.c:2019:7: warning: implicit declaration of function ‘yyerror’; did you mean ‘yyerrok’? [-Wimplicit-function-declaration]
olvwmrc.y: At top level:
olvwmrc.y:564:0: warning: "YYDEBUG" redefined
 #define YYDEBUG 1

y.tab.c:174:0: note: this is the location of the previous definition
olvwmrc.y:571:1: warning: conflicting types for ‘yyerror’
 yyerror(s)
 ^~~~~~~
y.tab.c:2019:7: note: previous implicit declaration of ‘yyerror’ was here
olvwmrc.y: In function ‘yyerror’:
olvwmrc.y:578:3: error: ‘yytext’ undeclared (first use in this function); did you mean ‘yypact’?
   yytext);
   ^~~~~~
   yypact
olvwmrc.y:578:3: note: each undeclared identifier is reported only once for each function it appears in
olvwmrc.y: In function ‘InitOlvwmRC’:
olvwmrc.y:1298:26: error: ‘yyin’ undeclared (first use in this function); did you mean ‘yyr2’?
     if (path == NULL || (yyin = fopen(path, "r")) == NULL)
                          ^~~~
                          yyr2
<builtin>: recipe for target 'olvwmrc.o' failed
make: *** [olvwmrc.o] Error 1
```

OS: Linux, Ubuntu 18.04 : Linux ubuntu1804 4.15.0-213-generic #224-Ubuntu SMP Mon Jun 19 13:30:12 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
Architecture: x86-64

Kindest regards,

Richard Crossley.
